### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'validate'

### ISSUE THREAD

**Issue by valuex** [davidshepherd7/ankicli#8]
Env:  Anki 2.0.47 + AnkiConnect 5 on Win10 64-bit  
While trying ankicli, the following error appears:
Please  help to check this. Thanks
```
Traceback (most recent call last):
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 444, in advance
    self.server.advance()
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 203, in advance
    self.advanceClients()
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 218, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 218, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 147, in advance
    self.writeBuff += self.handler(req)
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 237, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 451, in handler
    return getattr(self, action)(**(request.get('params') or {}))
  File "C:\Users\123\AppData\Roaming\Anki2\addons\ankiconnect.py", line 478, in api_addNotes
    if note.validate():
AttributeError:'dict' object has no attribute 'validate'
```

**Comment by valuex** [comment]
No problem now.
The problem appears as I was using an old version of AnkiConnect.
